// flow-typed signature: 9e451201593e23a81fe9057ec367ec58
// flow-typed version: <<STUB>>/react-responsive_v^10.0.0/flow_v0.246.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive/dist/cjs' {
  declare module.exports: any;
}

declare module 'react-responsive/dist/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive/dist/cjs/index' {
  declare module.exports: $Exports<'react-responsive/dist/cjs'>;
}
declare module 'react-responsive/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-responsive/dist/cjs'>;
}
declare module 'react-responsive/dist/esm/index' {
  declare module.exports: $Exports<'react-responsive/dist/esm'>;
}
declare module 'react-responsive/dist/esm/index.js' {
  declare module.exports: $Exports<'react-responsive/dist/esm'>;
}
