// flow-typed signature: f6e9026c76b6a9871c17a1bd3b75da1d
// flow-typed version: <<STUB>>/react-error-boundary_v^4.0.13/flow_v0.246.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-error-boundary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-error-boundary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-error-boundary/dist/react-error-boundary.cjs' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/react-error-boundary.development.cjs' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/react-error-boundary.development.esm' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/react-error-boundary.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-error-boundary/dist/react-error-boundary.cjs.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.cjs'>;
}
declare module 'react-error-boundary/dist/react-error-boundary.development.cjs.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.development.cjs'>;
}
declare module 'react-error-boundary/dist/react-error-boundary.development.esm.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.development.esm'>;
}
declare module 'react-error-boundary/dist/react-error-boundary.esm.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/react-error-boundary.esm'>;
}
